import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/navbar/Navbar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yaic</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <h1>Home</h1>
    </div>
  );
};

export default Home;
